(function() {var implementors = {};
implementors["fractal_api"] = ["impl <a class='trait' href='fractal_dto/trait.FromDTO.html' title='fractal_dto::FromDTO'>FromDTO</a>&lt;<a class='struct' href='fractal_dto/v1/oauth/struct.ClientInfoDTO.html' title='fractal_dto::v1::oauth::ClientInfoDTO'>ClientInfoDTO</a>&gt; for <a class='struct' href='fractal_api/v1/types/struct.ClientInfo.html' title='fractal_api::v1::types::ClientInfo'>ClientInfo</a>","impl <a class='trait' href='fractal_dto/trait.FromDTO.html' title='fractal_dto::FromDTO'>FromDTO</a>&lt;<a class='struct' href='fractal_dto/v1/user/struct.ProfileDTO.html' title='fractal_dto::v1::user::ProfileDTO'>ProfileDTO</a>&gt; for <a class='struct' href='fractal_api/v1/types/struct.Profile.html' title='fractal_api::v1::types::Profile'>Profile</a>","impl <a class='trait' href='fractal_dto/trait.FromDTO.html' title='fractal_dto::FromDTO'>FromDTO</a>&lt;<a class='struct' href='fractal_dto/v1/user/struct.UserDTO.html' title='fractal_dto::v1::user::UserDTO'>UserDTO</a>&gt; for <a class='struct' href='fractal_api/v1/types/struct.User.html' title='fractal_api::v1::types::User'>User</a>","impl <a class='trait' href='fractal_dto/trait.FromDTO.html' title='fractal_dto::FromDTO'>FromDTO</a>&lt;<a class='struct' href='fractal_dto/v1/transactions/struct.TransactionDTO.html' title='fractal_dto::v1::transactions::TransactionDTO'>TransactionDTO</a>&gt; for <a class='struct' href='fractal_api/v1/types/struct.Transaction.html' title='fractal_api::v1::types::Transaction'>Transaction</a>","impl <a class='trait' href='fractal_dto/trait.FromDTO.html' title='fractal_dto::FromDTO'>FromDTO</a>&lt;<a class='struct' href='fractal_dto/v1/friends/struct.PendingFriendRequestDTO.html' title='fractal_dto::v1::friends::PendingFriendRequestDTO'>PendingFriendRequestDTO</a>&gt; for <a class='struct' href='fractal_api/v1/types/struct.PendingFriendRequest.html' title='fractal_api::v1::types::PendingFriendRequest'>PendingFriendRequest</a>","impl <a class='trait' href='fractal_dto/trait.FromDTO.html' title='fractal_dto::FromDTO'>FromDTO</a>&lt;<a class='struct' href='fractal_dto/v1/oauth/struct.AccessTokenDTO.html' title='fractal_dto::v1::oauth::AccessTokenDTO'>AccessTokenDTO</a>&gt; for <a class='struct' href='fractal_api/v1/oauth/struct.AccessToken.html' title='fractal_api::v1::oauth::AccessToken'>AccessToken</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
